name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.17"]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: dependencies
      run: |
       npm install
      env:
        CI: true
    - name: compile
      run: |
       tsc --noEmit
    - name: test
      run: |
       npm run test