name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
          # will assign a random free host port
          - 5432/tcp
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        node-version: ["10.17"]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
       npm install
      env:
        CI: true
    - name: compile
      run: |
       tsc > null
    - name: run unit tests
      run: |
       npm run test
    - name: build
      run: |
       docker build -t stargrapht:latest .
    - name: initPostgre
      run: |
       npm run init
    - name: e2e test
      run: |
       docker run -p 3000:3000 stargrapht:latest && npm run e2e

       